### ISSUE TITLE
Does this plugin work on ios?

### ISSUE THREAD

**Issue by DenMarty** [DiRaizel/navigation_with_mapbox#1]
Hi DiRaizel,

I'm currently trying to implement navigation in my app, and as a result I came across your plugin. 
I tried it on Android and it works perfectly!

So I have a question: Does this plugin work on ios?
When I try to run a route on ios, nothing happens.

**Comment by DiRaizel** [comment]
Hi DenMarty, 

The operation in ios is still under development, now I have other pending projects and I think it will take me a while to get that update

**Comment by DiRaizel** [comment]
I already added the navigation for ios, I will close this problem
