### ISSUE TITLE
Error map lanching navigator

### ISSUE THREAD

**Issue by Diielle** [DiRaizel/navigation_with_mapbox#7]
Hi,
I am testing the package with a basic example: I copied the code found here 
[link](https://pub.dev/packages/navigation_with_mapbox/example)
into the main.

After pressing the button for Android the screen shows the mapbox logo but instead of the map everything is black.
In the console I see:

`W/Mapbox  (15149): [RouterFailure(url=https://api.mapbox.com/directions/v5/mapbox/driving/7.322028,45.72911;-75.923914,4.759335?geometries=polyline6&alternatives=true&overview=full&steps=true&bearings=0%2C45%3B&layers=%3B&continue_straight=true&annotations=congestion_numeric%2Cmaxspeed%2Cclosure%2Cspeed%2Cduration%2Cdistance&language=es&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=true&access_token=redacted, routerOrigin=com.mapbox.navigation.base.route.RouterOrigin$Offboard@fab2472, message=Not Authorized - Invalid Token, code=0, throwable=null)]`

Is the error caused by the fact that it cannot read the key? I put the private one in grandle.properties and the public one in strings.xml...

What am I doing wrong?
Thank you.

**Comment by ellexaD** [comment]
I had written a key wrong, sorry

**Comment by Diielle** [comment]
I had written a key wrong, sorry.
Can you delete the issue?
